# .gitpod.yml
image: gitpod/workspace-full  # or any suitable base image with Python

tasks:
  - name: install mamba and pangrelos_uq environment
    init: |
      echo "Downloading mambaforge..."
      curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
      echo "Installing mambaforge..."
      bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
      export PATH="/workspace/conda/bin:$PATH"
      /workspace/conda/bin/conda init bash
      source ~/.bashrc
      /workspace/conda/bin/conda env create -f environment.yml
      echo "/workspace/conda/bin/conda activate pangeos_uq" >> ~/.bashrc
      /workspace/conda/bin/conda activate pangeos_uq
      which python
      
  - name: Set up conda
    command: |
      # Activate the conda environment
      export PATH="/workspace/conda/bin:$PATH"
      /workspace/conda/bin/conda init bash
      source ~/.bashrc
      /workspace/conda/bin/conda activate pangeos_uq

  - name: start jupyter lab
    command: |
      export PATH="/workspace/conda/bin:$PATH"
      /workspace/conda/bin/conda init bash
      source ~/.bashrc
      /workspace/conda/bin/conda activate pangeos_uq
      # Launch JupyterLab on a specified port (8888 is default)
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''

ports:
  - port: 8888
    onOpen: open-browser  # Automatically open the JupyterLab interface in the browser

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers

# image: gitpod/workspace-base

# tasks:
# - name: install mamba and pangrelos_uq environment
#   init: |
#     curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
#     bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
#     /workspace/conda/bin/mamba init bash

#     source ${HOME}/.bashrc

#     mamba env create  --file /workspace/pangeos_uq/environment.yml

#     mamba clean --all -y

#     mamba activate pangeos_uq

#     mkdir -p "$PWD/.vscode";
#     cat << 'EOF' > "$PWD/.vscode/settings.json"
#     {
#         "python.defaultInterpreterPath": "/workspace/conda/env/pangeos_uq/bin/mamba",
#         "python.pythonPath": "/workspace/conda/env/pangeos_uq",
#     }
#     EOF
#     cat << 'EOF' > "$PWD/.vscode/.env"
#     EOF

#     cd /workspace

#   command: |
#     /workspace/conda/bin/mamba init bash
#     source ~/.bashrc
#     mamba activate pangeos_uq
#     mkdir -p "$PWD/.vscode";
#     cat << 'EOF' > "$PWD/.vscode/settings.json"
#     {
#         "python.defaultInterpreterPath": "/workspace/conda/env/pangeos_uq/bin/mamba",
#         "python.pythonPath": "/workspace/conda/env/pangeos_uq",
#     }
#     EOF
#     cat << 'EOF' > "$PWD/.vscode/.env"
#     EOF

#     cd /workspace

#     echo "Starting Jupyter Lab in the notebooks folder..."
#     jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --notebook-dir=/workspace/pangeos_uq/notebooks

# ports:
#   - port: 8888
#     onOpen: open-browser
#     visibility: public

# vscode:
#   extensions:
#     - ms-python.python
#     - ms-toolsai.jupyter