tasks:
  - name: setup
    init: |
      pushd /workspace
      wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      popd
      # bootstrap activation commands for other tasks to reuse
      cat <<EOT > /workspace/bin/activate-env.sh
      export MAMBA_ROOT_PREFIX=/workspace/.micromamba
      export MAMBA_EXE=/workspace/bin/micromamba
      $(/workspace/bin/micromamba shell hook --shell=bash)
      micromamba config append channels jgomezdans conda-forge
      export JUPYTER_PREFER_ENV_PATH=1
      micromamba activate
      EOT
      source /workspace/bin/activate-env.sh
      micromamba install -n base -y -f /workspace/pangeos_uq/environment.yml
      gp sync-done setup
    command: |
      gp sync-done setup
      source /workspace/bin/activate-env.sh
      jupyter lab --no-browser --ServerApp.allow_remote_access=True --ServerApp.token=''


ports:
  - port: 8888