# .gitpod.yml
image: condaforge/mambaforge # or any suitable base image with Python

tasks:
  - name: install mamba and pangrelos_uq environment
    init: |
      # Source Conda's initialization script
      . /opt/conda/etc/profile.d/conda.sh
      conda activate base

      # Create the environment in a user-writable directory (e.g., /workspace)
      conda env create --prefix /workspace/conda-env --file /workspace/pangeos_uq/environment.yml 
      mamba clean --all -y

      # Activate the environment in future terminal sessions
      echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
      echo "conda activate /workspace/conda-env" >> ~/.bashrc

      # Set up VSCode to use the Conda environment
      mkdir -p /workspace/.vscode
      echo '{"python.pythonPath": "/workspace/conda-env/bin/python"}' > /workspace/.vscode/settings.json
      

  - name: start jupyter lab
    command: |
      # Activate the Conda environment
      . /opt/conda/etc/profile.d/conda.sh
      conda activate /workspace/conda-env

      # Launch JupyterLab
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''

ports:
  - port: 8888
    onOpen: open-browser  # Automatically open the JupyterLab interface in the browser

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers

# image: gitpod/workspace-base

# tasks:
# - name: install mamba and pangrelos_uq environment
#   init: |
#     curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
#     bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
#     /workspace/conda/bin/mamba init bash

#     source ${HOME}/.bashrc

#     mamba env create  --file /workspace/pangeos_uq/environment.yml

#     mamba clean --all -y

#     mamba activate pangeos_uq

#     mkdir -p "$PWD/.vscode";
#     cat << 'EOF' > "$PWD/.vscode/settings.json"
#     {
#         "python.defaultInterpreterPath": "/workspace/conda/env/pangeos_uq/bin/mamba",
#         "python.pythonPath": "/workspace/conda/env/pangeos_uq",
#     }
#     EOF
#     cat << 'EOF' > "$PWD/.vscode/.env"
#     EOF

#     cd /workspace

#   command: |
#     /workspace/conda/bin/mamba init bash
#     source ~/.bashrc
#     mamba activate pangeos_uq
#     mkdir -p "$PWD/.vscode";
#     cat << 'EOF' > "$PWD/.vscode/settings.json"
#     {
#         "python.defaultInterpreterPath": "/workspace/conda/env/pangeos_uq/bin/mamba",
#         "python.pythonPath": "/workspace/conda/env/pangeos_uq",
#     }
#     EOF
#     cat << 'EOF' > "$PWD/.vscode/.env"
#     EOF

#     cd /workspace

#     echo "Starting Jupyter Lab in the notebooks folder..."
#     jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --notebook-dir=/workspace/pangeos_uq/notebooks

# ports:
#   - port: 8888
#     onOpen: open-browser
#     visibility: public

# vscode:
#   extensions:
#     - ms-python.python
#     - ms-toolsai.jupyter