# .gitpod.yml

image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Initializing workspace with Conda environment"
    command: |
      echo "Starting Jupyter Lab in the notebooks folder..."
      jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --notebook-dir=/workspace/notebooks

ports:
  - port: 8888
    onOpen: open-browser

# Disable VSCode by not including the vscode section
