# .gitpod.yml

image: gitpod/workspace-base

tasks:
- name: install mamba and pangrelos
  init: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

    mamba env create  --file /workspace/pangeos_uq/environment.yml

    mamba clean --all -y

    mamba activate pangeos_uq

    cd /workspace

  command: |
    /workspace/conda/bin/mamba init bash
    source ~/.bashrc
    mamba activate pangeos_uq
    echo "Starting Jupyter Lab in the notebooks folder..."
    jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --notebook-dir=/workspace/pangeos_uq/notebooks

ports:
  - port: 8888
    onOpen: open-browser

