tasks:
  - init: |
      # Set up environment
      conda env create -f environment.yml
      conda activate pangeos_uq
      pip install -e .
    command: |
      # Start JupyterLab
      jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token=''

ports:
  - port: 8888
    onOpen: open-browser

vscode:
  extensions:
    - ms-toolsai.jupyter

# Pre-open the notebooks folder in Jupyter Lab
onStart:
  - command: |
      mkdir -p /workspace/notebooks
      jupyter lab --NotebookApp.notebook_dir=/workspace/notebooks
