image: gitpod/workspace-full

tasks:
  - init: |
      echo "Downloading and installing Miniforge..."
      wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
      bash Miniforge3-Linux-x86_64.sh -b -p ~/miniforge3

      echo "Initializing conda..."
      source ~/miniforge3/bin/activate
      conda init bash

      echo "Creating conda environment..."
      conda env create -f environment.yml || echo "Failed to create conda environment"

      echo "Activating conda environment"
      conda activate pangeos_uq

      echo "Installing Python package"
      pip install -e . || echo "Failed to install package"
      
      echo "Prebuild complete"
    command: |
      echo "Activating conda environment and starting Jupyter Lab..."
      source ~/miniforge3/bin/activate
      conda activate pangeos_uq
      jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token=''

ports:
  - port: 8888
    onOpen: open-browser

vscode:
  extensions:
    - ms-toolsai.jupyter
