name: pangeos_uq
channels:
    - jgomezdans
    - conda-forge
dependencies:
    - python>3.11
    - numpy<2.0
    - scipy
    - jupyterlab
    - matplotlib
    - seaborn
    - ipykernel
    - jupyter_client
    - matplotlib-inline
    - ipython
    - ipympl
    - ipywidgets>7.6.0
    - h5py
    - pandas
    - tqdm
    - prosail
    - pangeos_uq
    - pip
    - pip:
        - pcse
        - git+https://github.com/jgomezdans/gp_emulator
