name: pangeos_uq
channels:
    - jgomezdans
    - conda-forge
dependencies:
    - python>3.11
    - numpy<2.0
    - scipy
    - jupyterlab
    - matplotlib
    - seaborn
    - ipykernel
    - ipympl
    - ipywidgets>7.6.0
    - h5py
    - pandas
    - tqdm
    - git
    - pip
    - pip:
        - pcse
        - git+https://github.com/jgomezdans/gp_emulator
        - git+https://github.com/jgomezdans/prosail
        - git+https://github.com/jgomezdans/pangeos_uq